In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('raw_data.csv')

In [3]:
df

,iso_code,location,date,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
1,AFG,Afghanistan,2020-01-01,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
2,AFG,Afghanistan,2020-01-02,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
3,AFG,Afghanistan,2020-01-03,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
4,AFG,Afghanistan,2020-01-04,0.0,0.0,0.00,38928341,1803.987,0.498,#NUM!,#NUM!,#NUM!,17.477233,7.497754494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50413,ZWE,Zimbabwe,2020-10-15,8055.0,231.0,76.85,14862927,1899.775,0.535,8.994048296,5.442417711,4.34185547,16.514381,7.549490737
50414,ZWE,Zimbabwe,2020-10-16,8075.0,231.0,76.85,14862927,1899.775,0.535,8.996528148,5.442417711,4.34185547,16.514381,7.549490737
50415,ZWE,Zimbabwe,2020-10-17,8099.0,231.0,76.85,14862927,1899.775,0.535,8.999495876,5.442417711,4.34185547,16.514381,7.549490737
50416,ZWE,Zimbabwe,2020-10-18,8110.0,231.0,76.85,14862927,1899.775,0.535,9.000853147,5.442417711,4.34185547,16.514381,7.549490737
50417,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535,9.00540504,5.442417711,4.34185547,16.514381,7.549490737

In [4]:
df.isnull().sum()

iso_code                       0
location                       0
date                           0
total_cases                 3094
total_deaths               11190
stringency_index            7126
population                     0
gdp_per_capita              5712
human_development_index     6202
Unnamed: 9                     0
Unnamed: 10                    0
Unnamed: 11                    0
Unnamed: 12                    0
Unnamed: 13                    0
dtype: int64

In [5]:
location = df['location'].value_counts()

In [8]:
location.keys()

Index(['Afghanistan', 'Algeria', 'Bahrain', 'Armenia', 'Austria', 'Belarus',
       'Australia', 'Azerbaijan', 'France', 'Finland',
       ...
       'Bonaire Sint Eustatius and Saba', 'Falkland Islands', 'South Sudan',
       'Sao Tome and Principe', 'Yemen', 'Tajikistan', 'Comoros', 'Lesotho',
       'Hong Kong', 'Solomon Islands'],
      dtype='object', name='location', length=210)

In [25]:
df[df['location'] == 'Andorra']['gdp_per_capita'].isnull().sum()

np.int64(226)

In [26]:
df[df['location'] == 'Algeria']['gdp_per_capita'].isnull().sum()

np.int64(0)

In [27]:
def check_the_isNull(loc_name):
    if df[df['location'] == loc_name]['gdp_per_capita'].isnull().sum() == 0:
        return False
    else:
        return True

In [28]:
check_the_isNull("india")

False

In [29]:
check_the_isNull("Andorra")

True

In [30]:
is_null_location = []

for i in location.keys():
    if check_the_isNull(i):
        is_null_location.append(i)
len(is_null_location)

26

In [32]:
gdp_per_capita_values =[256580,32600,66108,42414,186400,27461,56496,509,20501,20738,35600,41800,56600,61700,52500,34000,31100,84600,572,37000,29100,16583,34200,18220,23700,70800]

In [33]:
def check_the_isNull(loc_name,values):
    df.loc[df['location'] == loc_name,'gdp_per_capita'] = values

In [34]:
i = 0
while i<len(gdp_per_capita_values):
    check_the_isNull(is_null_location[i],gdp_per_capita_values[i])
    i = i+1

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50418 entries, 0 to 50417
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   iso_code                 50418 non-null  object
 1   location                 50418 non-null  object
 2   date                     50418 non-null  object
 3   total_cases              47324 non-null  float64
 4   total_deaths             39228 non-null  float64
 5   stringency_index         43292 non-null  float64
 6   population               50418 non-null  int64
 7   gdp_per_capita           50418 non-null  float64
 8   human_development_index  44216 non-null  float64
 9   Unnamed: 9               50418 non-null  object
 10  Unnamed: 10              50418 non-null  object
 11  Unnamed: 11              50418 non-null  object
 12  Unnamed: 12              50418 non-null  float64
 13  Unnamed: 13              50418 non-null  object
dtypes: float64(6), int64(1), object(7)
memory usage: 5.4+ MB

In [36]:
def check_the_isNull(loc_name):
    if df[df['location'] == loc_name]['human_development_index'].isnull().sum() == 0:
        return False
    else:
        return True

is_null_location = []

for i in location.keys():
    if check_the_isNull(i):
        is_null_location.append(i)
len(is_null_location)

28

In [ ]:
human_development_index_values  = [
    0.931,            # San Marino
    0.846,            # Monaco (2019 estimate)
    0.910,            # Taiwan (2019 estimate)
    0.896,            # Faroe Islands (2017 estimate)
    0.872,            # Sint Maarten (Dutch part) (2017 estimate)
    0.800,            # Vatican (data available from 2013 estimate)
    0.285,            # Somalia (2019 estimate)
    0.891,            # Aruba (2019 estimate)
    0.847,            # Curacao (2017 estimate)
    0.759,            # French Polynesia (2018 estimate)
    0.91,             # Guam (2016 estimate)
    0.956,            # Bermuda (2019 estimate)
    0.928,            # Cayman Islands (2017 estimate)
    0.840,            # Greenland (2017 estimate)
    0.926,            # Jersey (2019 estimate)
    0.851,            # Gibraltar (2016 estimate)
    0.900,            # Guernsey (2016 estimate)
    0.803,            # Montserrat (2015 estimate)
    0.830,            # New Caledonia (2015 estimate)
    0.914,            # Isle of Man (2018 estimate)
    0.916,            # United States Virgin Islands (2017 estimate)
    0.920,            # Turks and Caicos Islands (2017 estimate)
    0.900,            # Anguilla (2016 estimate)
    0.875,            # British Virgin Islands (2018 estimate)
    0.860,            # Puerto Rico (2018 estimate)
    0.830,            # Northern Mariana Islands (2016 estimate)
    0.870,            # Bonaire Sint Eustatius and Saba (2017 estimate)
    0.780             # Falkland Islands (2015 estimate)
]

In [40]:

print(len(human_development_index_values))
print(len(is_null_location))

28
28

In [41]:
def check_the_isNull(loc_name,values):
    df.loc[df['location'] == loc_name,'human_development_index'] = values

i = 0
while i<len(human_development_index_values):
    check_the_isNull(is_null_location[i],human_development_index_values[i])
    i = i+1

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50418 entries, 0 to 50417
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   iso_code                 50418 non-null  object
 1   location                 50418 non-null  object
 2   date                     50418 non-null  object
 3   total_cases              47324 non-null  float64
 4   total_deaths             39228 non-null  float64
 5   stringency_index         43292 non-null  float64
 6   population               50418 non-null  int64
 7   gdp_per_capita           50418 non-null  float64
 8   human_development_index  50418 non-null  float64
 9   Unnamed: 9               50418 non-null  object
 10  Unnamed: 10              50418 non-null  object
 11  Unnamed: 11              50418 non-null  object
 12  Unnamed: 12              50418 non-null  float64
 13  Unnamed: 13              50418 non-null  object
dtypes: float64(6), int64(1), object(7)
memory usage: 5.4+ MB

In [45]:
df['stringency_index'].median()

np.float64(61.11)

In [46]:
df['stringency_index'].mean()

np.float64(56.16202208260186)

In [50]:
df.fillna({'stringency_index': 61}, inplace=True)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50418 entries, 0 to 50417
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   iso_code                 50418 non-null  object
 1   location                 50418 non-null  object
 2   date                     50418 non-null  object
 3   total_cases              47324 non-null  float64
 4   total_deaths             39228 non-null  float64
 5   stringency_index         50418 non-null  float64
 6   population               50418 non-null  int64
 7   gdp_per_capita           50418 non-null  float64
 8   human_development_index  50418 non-null  float64
 9   Unnamed: 9               50418 non-null  object
 10  Unnamed: 10              50418 non-null  object
 11  Unnamed: 11              50418 non-null  object
 12  Unnamed: 12              50418 non-null  float64
 13  Unnamed: 13              50418 non-null  object
dtypes: float64(6), int64(1), object(7)
memory usage: 5.4+ MB

In [54]:
df.dropna(inplace=True)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39211 entries, 0 to 50417
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   iso_code                 39211 non-null  object
 1   location                 39211 non-null  object
 2   date                     39211 non-null  object
 3   total_cases              39211 non-null  float64
 4   total_deaths             39211 non-null  float64
 5   stringency_index         39211 non-null  float64
 6   population               39211 non-null  int64
 7   gdp_per_capita           39211 non-null  float64
 8   human_development_index  39211 non-null  float64
 9   Unnamed: 9               39211 non-null  object
 10  Unnamed: 10              39211 non-null  object
 11  Unnamed: 11              39211 non-null  object
 12  Unnamed: 12              39211 non-null  float64
 13  Unnamed: 13              39211 non-null  object
dtypes: float64(6), int64(1), object(7)
memory usage: 4.5+ MB

In [57]:
df.drop(columns=['Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13'],inplace=True)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39211 entries, 0 to 50417
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   iso_code                 39211 non-null  object
 1   location                 39211 non-null  object
 2   date                     39211 non-null  object
 3   total_cases              39211 non-null  float64
 4   total_deaths             39211 non-null  float64
 5   stringency_index         39211 non-null  float64
 6   population               39211 non-null  int64
 7   gdp_per_capita           39211 non-null  float64
 8   human_development_index  39211 non-null  float64
dtypes: float64(5), int64(1), object(3)
memory usage: 3.0+ MB

In [59]:
df

,iso_code,location,date,total_cases,total_deaths,stringency_index,population,gdp_per_capita,human_development_index
0,AFG,Afghanistan,2019-12-31,0.0,0.0,0.00,38928341,1803.987,0.498
1,AFG,Afghanistan,2020-01-01,0.0,0.0,0.00,38928341,1803.987,0.498
2,AFG,Afghanistan,2020-01-02,0.0,0.0,0.00,38928341,1803.987,0.498
3,AFG,Afghanistan,2020-01-03,0.0,0.0,0.00,38928341,1803.987,0.498
4,AFG,Afghanistan,2020-01-04,0.0,0.0,0.00,38928341,1803.987,0.498
...,...,...,...,...,...,...,...,...,...
50413,ZWE,Zimbabwe,2020-10-15,8055.0,231.0,76.85,14862927,1899.775,0.535
50414,ZWE,Zimbabwe,2020-10-16,8075.0,231.0,76.85,14862927,1899.775,0.535
50415,ZWE,Zimbabwe,2020-10-17,8099.0,231.0,76.85,14862927,1899.775,0.535
50416,ZWE,Zimbabwe,2020-10-18,8110.0,231.0,76.85,14862927,1899.775,0.535
50417,ZWE,Zimbabwe,2020-10-19,8147.0,231.0,76.85,14862927,1899.775,0.535

In [60]:
df.to_csv('cleaning.csv')